### ISSUE TITLE
Update The remaining code in the repository 

### ISSUE THREAD

**Issue by valleyofblackpanther** [Web-Arch-Tech/Comrades_Project#1]
It would be great if you guys can add the remaining the code to the repository, I'' just list down the missing code that needs to be added. 
**i)** signup need to be altered a bit. 
**ii)** volunteer can be done with php by making a connection with the database. 
**iii)** there's a lot of space between the screens and the elements too. We can decrease it so the elements come under the margin. 
**iv)** @rahulmarsh push all the code to main repository that you have created.

**Comment by valleyofblackpanther** [comment]
thanks for the repo @Shady-45

**Comment by Shady-45** [comment]
made changes  to the signup page @valleyofblackpanther
